module.exports = {
  preset: 'react-native',
  testEnvironment: 'node',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  roots: ['<rootDir>/components', '<rootDir>/screens', '<rootDir>/hooks', '<rootDir>/app', '<rootDir>/providers'],
  testMatch: [
    '<rootDir>/components/**/__tests__/**/*.(js|jsx|ts|tsx)',
    '<rootDir>/components/**/*.(test|spec).(js|jsx|ts|tsx)',
    '<rootDir>/screens/**/__tests__/**/*.(js|jsx|ts|tsx)',
    '<rootDir>/screens/**/*.(test|spec).(js|jsx|ts|tsx)',
    '<rootDir>/hooks/**/__tests__/**/*.(js|jsx|ts|tsx)',
    '<rootDir>/hooks/**/*.(test|spec).(js|jsx|ts|tsx)',
    '<rootDir>/app/**/__tests__/**/*.(js|jsx|ts|tsx)',
    '<rootDir>/app/**/*.(test|spec).(js|jsx|ts|tsx)',
    '<rootDir>/providers/**/__tests__/**/*.(js|jsx|ts|tsx)',
    '<rootDir>/providers/**/*.(test|spec).(js|jsx|ts|tsx)'
  ],
  transform: {
    '^.+\\.(ts|tsx)$': 'babel-jest',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(@react-native|react-native|expo|@expo|@expo-google-fonts|expo-font|expo-asset|expo-constants|expo-linking|expo-router|@react-native-community|@react-native-picker|react-native-svg|react-native-gesture-handler|react-native-screens|react-native-safe-area-context|@react-native-async-storage)/)',
  ],
  moduleNameMapper: {
    '^components/(.*)$': '<rootDir>/components/$1',
    '^themes/(.*)$': '<rootDir>/themes/$1',
    '^assets/(.*)$': '<rootDir>/assets/$1',
    '^graphql/(.*)$': '<rootDir>/graphql/$1',
    '^screens/(.*)$': '<rootDir>/screens/$1',
    '^hooks/(.*)$': '<rootDir>/hooks/$1',
    '^providers/(.*)$': '<rootDir>/providers/$1',
    '^types/(.*)$': '<rootDir>/types/$1',
    '^utils/(.*)$': '<rootDir>/utils/$1',
    '\\.(svg|png|jpg|jpeg|gif)$': 'jest-transform-stub',
  },
  collectCoverageFrom: [
    'components/**/*.{js,jsx,ts,tsx}',
    'screens/**/*.{js,jsx,ts,tsx}',
    'hooks/**/*.{js,jsx,ts,tsx}',
    'app/**/*.{js,jsx,ts|tsx}',
    'providers/**/*.{js,jsx,ts,tsx}',
    '!**/*.d.ts',
    '!**/__tests__/**',
    '!**/index.{js,jsx,ts,tsx}',
    '!**/node_modules/**',
  ],
};