export const mockData = {
  user: {
    id: "1",
    name: "Faith",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  insights: {
    id: "1",
    weather: {
      city: "San Francisco",
      condition: "Sunny",
      temperature: 14,
    },
    nextDestination: {
      location: "Tokyo, Japan",
      daysAway: 14,
    },
    progress: {
      completed: 15,
      yearlyGoal: 25,
      percentage: 60,
    },
    recentAchievement: "Completed hiking challenge",
  },
  upcomingEvents: [
    {
      id: "1",
      image:
        "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dHJhdmVsfGVufDB8fDB8fHww",
      title: "Beach Cleanup",
      date: "2023-10-15",
      location: "Santa Monica Beach",
    },
    {
      id: "2",
      image:
        "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&q=80&w=800",
      title: "Tech Conference",
      date: "2023-11-20",
      location: "Los Angeles Convention Center",
    },
    {
      id: "3",
      image:
        "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&q=80&w=800",
      title: "Art Exhibition",
      date: "2023-12-05",
      location: "Downtown Art Gallery",
    },
  ],
  bucketCategories: [
    { id: "1", name: "Movies", emoji: "🎬" },
    { id: "2", name: "Books", emoji: "📚" },
    { id: "3", name: "Cooking", emoji: "👩‍🍳" },
    { id: "4", name: "Travelling", emoji: "✈️" },
  ],
  upcomingActivities: [
    {
      id: "1",
      activity: "Skydiving in Dubai",
      image:
        "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=800",
      category: "Adventure",
      date: "2024-01-15",
      location: "Dubai, UAE",
    },
    {
      id: "2",
      activity: "Visit the Grand Canyon",
      image:
        "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&q=80&w=800",
      category: "Travel",
      date: "2024-02-10",
      location: "Arizona, USA",
    },
    {
      id: "3",
      activity: "Learn to play the guitar",
      image:
        "https://images.unsplash.com/photo-1511376777868-611b54f68947?auto=format&fit=crop&q=80&w=800",
      category: "Hobby",
      date: "2024-03-05",
      location: "Online",
    },
    {
      id: "4",
      activity: "Visit the Eiffel Tower",
      image:
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800",
      category: "Culture",
      date: "2024-04-20",
      location: "Paris, France",
    },
    {
      id: "5",
      activity: "Visit the Taj Mahal",
      image:
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800",
      category: "Culture",
      date: "2024-04-20",
      location: "Agra, India",
    },
  ],
  bucketItems: [
    {
      id: "1",
      title: "Learn to surf",
      description: "Take surfing lessons at Bondi Beach",
      completed: false,
      categoryId: "4",
    },
    {
      id: "2", 
      title: "Read 12 books this year",
      description: "Focus on personal development and fiction",
      completed: false,
      categoryId: "2",
    },
    {
      id: "3",
      title: "Watch Inception",
      description: "Finally watch this mind-bending movie",
      completed: true,
      categoryId: "1",
    },
  ],
};
export const emojiLibrary = [
  // Travel & Adventure
  { symbol: "🎯", description: "Target/Goals" },
  { symbol: "✈️", description: "Airplane/Travel" },
  { symbol: "🏔️", description: "Mountains" },
  { symbol: "🏖️", description: "Beach" },
  { symbol: "🏕️", description: "Camping" },
  { symbol: "🗺️", description: "World Map" },
  { symbol: "🧳", description: "Luggage" },
  { symbol: "🎒", description: "Backpack" },
  { symbol: "🚗", description: "Car" },
  { symbol: "🚢", description: "Ship" },
  { symbol: "🏰", description: "Castle" },
  { symbol: "🗽", description: "Statue of Liberty" },
  { symbol: "🎡", description: "Ferris Wheel" },
  { symbol: "🎢", description: "Roller Coaster" },
  { symbol: "🎠", description: "Carousel" },
  { symbol: "🌋", description: "Volcano" },
  { symbol: "🏜️", description: "Desert" },
  { symbol: "🏞️", description: "National Park" },
  { symbol: "🌊", description: "Ocean Wave" },
  { symbol: "🌅", description: "Sunrise" },

  // Arts & Creativity
  { symbol: "🎨", description: "Art Palette" },
  { symbol: "🎭", description: "Theater Masks" },
  { symbol: "🎪", description: "Circus" },
  { symbol: "🖼️", description: "Framed Picture" },
  { symbol: "✏️", description: "Pencil" },
  { symbol: "🖌️", description: "Paintbrush" },
  { symbol: "📸", description: "Camera" },
  { symbol: "🎬", description: "Movie Camera" },
  { symbol: "📹", description: "Video Camera" },
  { symbol: "🎤", description: "Microphone" },
  { symbol: "🎵", description: "Musical Note" },
  { symbol: "🎶", description: "Musical Notes" },
  { symbol: "🎸", description: "Guitar" },
  { symbol: "🎹", description: "Piano" },
  { symbol: "🎺", description: "Trumpet" },
  { symbol: "🥁", description: "Drums" },
  { symbol: "🎼", description: "Musical Score" },
  { symbol: "🎧", description: "Headphones" },
  { symbol: "📚", description: "Books" },
  { symbol: "✍️", description: "Writing" },

  // Sports & Fitness
  { symbol: "⚽", description: "Soccer Ball" },
  { symbol: "🏀", description: "Basketball" },
  { symbol: "🏈", description: "Football" },
  { symbol: "⚾", description: "Baseball" },
  { symbol: "🎾", description: "Tennis" },
  { symbol: "🏐", description: "Volleyball" },
  { symbol: "🏓", description: "Ping Pong" },
  { symbol: "🏸", description: "Badminton" },
  { symbol: "🥊", description: "Boxing" },
  { symbol: "🏋️", description: "Weightlifting" },
  { symbol: "🏃", description: "Running" },
  { symbol: "🚴", description: "Cycling" },
  { symbol: "🏊", description: "Swimming" },
  { symbol: "🏄", description: "Surfing" },
  { symbol: "⛷️", description: "Skiing" },
  { symbol: "🏇", description: "Horse Racing" },
  { symbol: "🧗", description: "Rock Climbing" },
  { symbol: "🤸", description: "Gymnastics" },
  { symbol: "🧘", description: "Meditation/Yoga" },
  { symbol: "💪", description: "Strength" },

  // Food & Dining
  { symbol: "🍕", description: "Pizza" },
  { symbol: "🍔", description: "Hamburger" },
  { symbol: "🌮", description: "Taco" },
  { symbol: "🍜", description: "Noodles" },
  { symbol: "🍣", description: "Sushi" },
  { symbol: "🍰", description: "Cake" },
  { symbol: "🧁", description: "Cupcake" },
  { symbol: "🍷", description: "Wine" },
  { symbol: "☕", description: "Coffee" },
  { symbol: "🍎", description: "Apple" },
  { symbol: "🥗", description: "Salad" },
  { symbol: "🍝", description: "Pasta" },
  { symbol: "🍲", description: "Hot Pot" },
  { symbol: "🥘", description: "Paella" },
  { symbol: "🍳", description: "Cooking" },
  { symbol: "🥞", description: "Pancakes" },
  { symbol: "🧀", description: "Cheese" },
  { symbol: "🍓", description: "Strawberry" },
  { symbol: "🥑", description: "Avocado" },
  { symbol: "🌶️", description: "Hot Pepper" },

  // Technology & Gaming
  { symbol: "🚀", description: "Rocket" },
  { symbol: "🎮", description: "Gaming" },
  { symbol: "🖥️", description: "Desktop Computer" },
  { symbol: "📱", description: "Mobile Phone" },
  { symbol: "⌚", description: "Smartwatch" },
  { symbol: "🔬", description: "Microscope" },
  { symbol: "🧪", description: "Test Tube" },
  { symbol: "⚡", description: "Lightning" },
  { symbol: "🔋", description: "Battery" },
  { symbol: "🛸", description: "UFO" },
  { symbol: "🤖", description: "Robot" },
  { symbol: "💻", description: "Laptop" },
  { symbol: "🖱️", description: "Computer Mouse" },
  { symbol: "⌨️", description: "Keyboard" },
  { symbol: "🕹️", description: "Joystick" },
  { symbol: "🎲", description: "Dice" },
  { symbol: "🧩", description: "Puzzle Piece" },
  { symbol: "🔭", description: "Telescope" },
  { symbol: "📡", description: "Satellite" },

  // Nature & Animals
  { symbol: "🌟", description: "Star" },
  { symbol: "🌺", description: "Hibiscus" },
  { symbol: "🌸", description: "Cherry Blossom" },
  { symbol: "🌷", description: "Tulip" },
  { symbol: "🌻", description: "Sunflower" },
  { symbol: "🌳", description: "Tree" },
  { symbol: "🍃", description: "Leaves" },
  { symbol: "🐝", description: "Bee" },
  { symbol: "🦋", description: "Butterfly" },
  { symbol: "🐢", description: "Turtle" },
  { symbol: "🦅", description: "Eagle" },
  { symbol: "🐺", description: "Wolf" },
  { symbol: "🦁", description: "Lion" },
  { symbol: "🐼", description: "Panda" },
  { symbol: "🐧", description: "Penguin" },
  { symbol: "🦉", description: "Owl" },
  { symbol: "🌙", description: "Crescent Moon" },
  { symbol: "☀️", description: "Sun" },
  { symbol: "⭐", description: "Star" },
  { symbol: "🌈", description: "Rainbow" },
];
